# ~~~~~ VCF Template~~~~~

# =============================================================================
# General Variables
# =============================================================================

# Reference name
REFNAME: "ebola_1976"

# Source to download references (ncbi or ensembl)
REF_SOURCE: "ncbi"


#PRJN number (only used in getdata_sra)
PRJNUMBER: "PRJNA257197"

# Project name
PRJNAME: "ebola_2014"


# =============================================================================
# Ref variables (source dependent)
# =============================================================================
# (optional) NCBI source variable
# Accession number 
ACC: "AF086833"

# (optional) Ensemble source variables
# Latin name of the species (case insensitive)
SPECIES_LATIN: "saccharomyces_cerevisiae" 
#Assembly number
ASSEMBLY: "R64-1-1"
# Release version
RELEASE: 112

# =============================================================================
# getdata.smk specific variables
# =============================================================================
# choose Data source for LOCAL or SRA 
#LOCAL: create a runinfo.csv from items under reads/{PRJNAME}
#SRA: if runinfo.csv exist: download SRRs from runinfo.csv, else query for runinfo.csv from SRA metadata
DSOURCE: "SRA"

# Get how many number of reads from original fastq
N: "10000"


# =============================================================================
# qc.smk specific variabble
# =============================================================================
# trim quality below a certain level
QUALITY: "30"

# Minimum length to keep
LENGTH: "15"


# =============================================================================
# dna_aligner.smk specific variabble
# =============================================================================
# choose alinger f(bwa, bowtie2, minimap2_sr (use lower case!!))
ALIGNER: "bwa"

# choose sam flag for bamfilter, can by generated using https://broadinstitute.github.io/picard/explain-flags.html
SAMFLAG: "3"

# choose Mapping Quality score for filter bam
MAPQ: "30"



# =============================================================================
# dna_vcf.smk specific variabble
# =============================================================================
# freebayes specific variable 
# viral/haploid: 1 ,   human/diploid: 2
PLOIDY: "1"

#SnpEFF RAM usage
#choose RAM usage for vcf annotation (default at 4g)
#this variable is used in rule download_snpEff_db vcfannotation and 
RAM: "4g"


