name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pyyaml
  - pandas
  - snakemake
  - biopython
# this is a snakemake portable env setup for newly installed 
