import os
import pandas as pd

# =============================================================================
# Setup and Configuration
# =============================================================================
PRJNAME = config.get("PRJNAME") 
if not PRJNAME:
    raise ValueError("ERROR: Specify PRJNAME via --config")

# Load project-specific configuration from the project directory
configfile: f"reads/{PRJNAME}/config.yaml"

# --- Mandatory Configuration Checks ---
if "REF" not in config or not isinstance(config["REF"], dict):
    raise ValueError("\n\n[CONFIGURATION ERROR]\nMissing 'REF' block structure in config.yaml!\n")

mandatory_ref_vars = {
    "SOURCE": "choose from ncbi or ensembl",
    "SPECIES": "Latin binomial name (e.g., saccharomyces_cerevisiae)",
    "ASSEMBLY": "Major assembly build designation (e.g., R64-2-1 or GRCh38)"
}

for var, description in mandatory_ref_vars.items():
    if not config["REF"].get(var):
        raise ValueError(
            f"\n\n[CONFIGURATION ERROR]\n"
            f"Variable 'REF -> {var}' is missing!\n"
            f"Description: {description}\n"
        )

# =============================================================================
# Unified Global Path & Context Variables
# =============================================================================
# REF block variables
ref_cfg  = config["REF"]
source   = ref_cfg["SOURCE"].lower()
species  = ref_cfg["SPECIES"].lower()
assembly = ref_cfg["ASSEMBLY"]
release  = ref_cfg.get("RELEASE", "")
acc = ref_cfg.get("ACC") or "GCF_000848505.1"

# Name variations for structural renaming rules
species_low = species.replace(" ", "_")
species_cap = species_low.capitalize()

# Path Roots
data_src = config.get("DATA_SOURCE", "SRA")
base_src = config.get("DATABASE_SOURCE", "snpeff").lower()

REFS_DIR = f"refs/{source}/{species_low}/{assembly}/{release}"
READS_DIR = f"reads/{PRJNAME}"
LOG_DIR = f"reads/{PRJNAME}/logs"
DATABASES_DIR = f"databases/{base_src}/{source}.{species}.{assembly}.{release}"

# aligner variables for path construction
dna_aligner = config.get("DNA_ALIGNER", "bwa").lower()
rna_aligner = config.get("RNA_ALIGNER", "star").lower()

# Tool Wildcard Constraint Configurations
DNA_ALIGNERS = ["bwa", "bowtie2", "minimap2_sr"]
RNA_SPLICED_ALIGNERS = ["star", "hisat2"]
RNA_PSEUDO_ALIGNERS = ["kallisto", "salmon"]

# RNAseq expression analyser
rna_exp_analyser = config.get("EXP_ANALYSER", "deseq2").lower()



# =============================================================================
# Helper Functions
# =============================================================================

def get_runinfo(wildcards):
    """
    Triggers checkpoints based on DATASOURCE from config.yaml (SRA or LOCAL)
    and resolves the correct runinfo file path dynamically.
    """
    dsource = config.get("DATASOURCE", "SRA").upper() 
    
    if dsource == "SRA":
        cp_output = checkpoints.getdata_sra.get(**wildcards).output.csv 
    elif dsource == "LOCAL":
        cp_output = checkpoints.getdata_local.get(**wildcards).output.csv 
    else:
        raise ValueError(f"Invalid DATASOURCE '{dsource}' in config. Must be SRA or LOCAL.")

    df = pd.read_csv(cp_output) 
    return df['Run'].tolist()


def get_refs(wildcards):
    """
    Dynamically routes pipeline requirements to the isolated database path layout.
    """
    if source == "ensembl":
        return {
            "fasta": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.fa",
            "gff": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.gff3",
            "gtf": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.gtf"
        }
    elif source == "ncbi":
        return {
            "fasta": f"{REFS_DIR}/{acc}.fa",
            "gff": f"{REFS_DIR}/{acc}.gff3",
            "gtf": f"{REFS_DIR}/{acc}.gtf"
        }
    else:
        raise ValueError(f"Unsupported REF_SOURCE target: {source}")


def get_qc(wildcards):
    """Generates QC report targets, merge by multiqc and forces fastq trimming."""
    samples = get_runinfo(wildcards)
    
    fastqc = expand("{rddir}/qc/{s}_{pair}_fastqc.html", 
                    rddir=READS_DIR, s=samples, pair=[1, 2])
    multiqc = [f"{READS_DIR}/qc/multiqc_report.html"]
    
    trim_r1 = expand("{rddir}/qc_trimmed/{s}_1_val_1.fq.gz", rddir=READS_DIR, s=samples)
    trim_r2 = expand("{rddir}/qc_trimmed/{s}_2_val_2.fq.gz", rddir=READS_DIR, s=samples)
  
    return multiqc + trim_r1 + trim_r2

def get_align_input(wildcards):
    """
    Directs the alignment rules to the correct quality-trimmed FASTQ files
    generated by the upstream trimming step.
    """
    return {
        "r1": f"{READS_DIR}/qc_trimmed/{wildcards.sample}_1_val_1.fq.gz",
        "r2": f"{READS_DIR}/qc_trimmed/{wildcards.sample}_2_val_2.fq.gz"
    }

# =============================================================================
# DNA and VCF Helper Functions
# =============================================================================

def get_dna_align(wildcards):
    """Align, generate bam and filtered bam."""
    samples = get_runinfo(wildcards)
    aligner = dna_aligner
    return expand("{rddir}/bam/filtered/{s}.{aln}.filtered.bam",
                  rddir=READS_DIR, s=samples, aln=aligner)

def get_dna_vcf(wildcards):
    """Generates vcf.gz, merged.vcf.gz, ann.vcf."""
    samples = get_runinfo(wildcards)
    aligner = dna_aligner 
    
    annvcf = f"{READS_DIR}/vcf/all_samples.{aligner}.ann.vcf.gz"
    anntbi = f"{READS_DIR}/vcf/all_samples.{aligner}.ann.vcf.gz.tbi"
    annstats = f"{READS_DIR}/vcf/all_samples.{aligner}.snpeff_stats.html"
    consensus = expand("{rddir}/vcf/consensus/{s}.{aln}.consensus.fa", 
                       rddir=READS_DIR, s=samples, aln=aligner)
  
    return [annvcf, anntbi, annstats] + consensus

# =============================================================================
# DNA Ridigity Helper Functions
# =============================================================================
def get_dna_rigid(wildcards): 
    """Generates rigidity profile tracks out of structural data layouts."""
    tsv = f"{READS_DIR}/dna_rigidity/rigidity_profile.tsv"
    bg = f"{READS_DIR}/dna_rigidity/rigidity_profile.bedGraph"
    return [tsv, bg]

# =============================================================================
# RNAseq Helper Functions
# =============================================================================
def get_rna_align(wildcards):
    """Determines exactly which files to build based on the RNA ALIGNER in config."""
    samples = get_runinfo(wildcards)
    aligner = rna_aligner
    
    if aligner in RNA_PSEUDO_ALIGNERS:
        # Determine the file name based on the tool
        target_file = "abundance.tsv" if aligner == "kallisto" else "quant.sf"
        
        # Match the path to the 'pseudo_individual' directory structure
        return expand("{rddir}/counts/pseudo_individual/{s}.{aln}/{filename}",
                      rddir=READS_DIR, s=samples, aln=aligner, filename=target_file)
    else:
        return expand("{rddir}/bam/{s}.{aln}.bam",
                      rddir=READS_DIR, s=samples, aln=aligner)

def get_rna_bigwig(wildcards):
    """Generates BigWig coverage targets for all samples processed with a spliced aligner."""
    samples = get_runinfo(wildcards)
    aligner = rna_aligner
    
    if aligner in RNA_SPLICED_ALIGNERS:
        return expand("{rddir}/bam/bigwig/{s}.{aln}.bw",
                      rddir=READS_DIR, s=samples, aln=aligner)
    return [] # Returns empty list for pseudo-aligners so it safely skips BigWig generation

def get_rna_counts(wildcards):
    """Compiles the single final merged CSV target path for both alignment styles."""
    aligner = rna_aligner
    
    if aligner in RNA_SPLICED_ALIGNERS:
        return [f"{READS_DIR}/counts/sequence/all_samples.{aligner}_counts.csv"]
    else:
        # Automatically routes to your new merge_pseudo matrix for Kallisto/Salmon
        return [f"{READS_DIR}/counts/pseudo/all_samples.{aligner}_pseudo_counts.csv"]

def get_rna_exp_analyser_output(wildcards):
    """Determines the RNA expression target path based on EXPRESSION_ANALYSER in config."""
    suffix = "counts.csv" if rna_aligner in RNA_SPLICED_ALIGNERS else "pseudo_counts.csv"
    return f"{READS_DIR}/expression/{rna_exp_analyser}_expression.{rna_aligner}_{suffix}"

def get_rna_tools_compare(wildcards):
    """Determines the comprehensive final target path array for the RNA-seq module."""
    return [
        f"{READS_DIR}/expression/cross_tool_comparison.csv",
        f"{READS_DIR}/expression/plots/diff_exp_venn_overlap.png"
    ]

def get_rna_report_outputs(wildcards):
    """Gathers all biological thresholds and quality control diagnostic plots."""
    return [
        f"{READS_DIR}/expression/significant_genes_thresholded.csv",
        f"{READS_DIR}/expression/plots/volcano_plot.png",
        f"{READS_DIR}/expression/plots/diagnostic_ma_plot.png",
        f"{READS_DIR}/expression/plots/diagnostic_pvalue_histogram.png",
        f"{READS_DIR}/expression/plots/pca_plot.png"
    ]

def get_rna_enrich_outputs(wildcards):
    """Generate heatmap and function enrichment study results."""
    return [
        f"{READS_DIR}/expression/plots/heatmap.png",
        f"{READS_DIR}/expression/enrichment_go_results.csv",
        f"{READS_DIR}/expression/plots/enrichment_go_dotplot.png",
    ]

# =============================================================================
# Chip-Seq Helper Functions
# =============================================================================

def get_chip_align(wildcards):
    """Align, generate bam and filtered bam from chipseq dataset."""
    samples = get_runinfo(wildcards)
    aligner = dna_aligner
    return expand("{rddir}/bam/filtered/{s}.{aln}.chip.filtered.bam",
                  rddir=READS_DIR, s=samples, aln=aligner)
                  
# =============================================================================
# Include Modular Rule Files
# =============================================================================
include: "toolbox/getdata.smk" 
include: "toolbox/qc.smk" 
include: "toolbox/dna_aligner.smk" 
include: "toolbox/dna_vcf.smk" 
include: "toolbox/cleanup.smk"
include: "toolbox/dna_rigidity.smk"
include: "toolbox/rna_aligner.smk"
include: "toolbox/rna_diff_exp.smk"
include: "toolbox/chip_aligner.smk"

# =============================================================================
# Terminal Rules
# =============================================================================
rule note:
    input:
    run:
        print("\n" + "="*50)
        print("THIS SNAKEFILE SERVES AS TERMINAL FOR BIOINFORMATIC TOOLBOX")
        print("Please specify a target rule:")
        print("Data/Reference Gathering")
        print("  snakemake runinfo           - Get runinfo for samples")
        print("  snakemake download_refs     - Download fa, gff3 and gtf files")
        print("  snakemake qc                - Download data and run QC")
        print("SNP/Variant Analysis")
        print("  snakemake dna_align         - Run DNA alignments")
        print("  snakemake dna_vcf           - Run DNA VCF")
        print("  snakemake dna_vcf_all       - Run QC, DNA Alignments and VCF")
        print("DNA Rigidity Scoring")
        print("  snakemake dna_rigid         - Run dna rigidity score on fasta")
        print("RNAseq Analysis")
        print("  snakemake rna_align         - Run RNA alignment")
        print("  snakemake rna_exp           - Run RNA expression analysis")
        print("  snakemake exp_tools_compare - (optional) Compare expression analysis tools deseq2 vs edger")
        print("  snakemake rna_report        - Evaluate expression data with pca, MA, p-value histagram and volcano plots,")
        print("                                generate csv for list of significantly different expressed genes")
        print("  snakemake rna_enrich        - Generate heatmap and perform functional enrichment study")
        print("  snakemake rna_all           - Gets samples and refs, run QC, rna align, exp, report and enrich")
        print("Clean up")
        print("  snakemake cleanup           - Clean up dummy R2 files from single end sequencing")
        print("="*50 + "\n")

rule runinfo:
    """Download runinfo.csv or create one from fastq files under reads/project_name"""
    input: get_runinfo

rule download_refs:
    """Utility run-target that safely maps upstream conversion assets."""
    input: 
        lambda wildcards: list(get_refs(wildcards).values())

rule qc:
    """QC for fastq files."""
    input: get_qc

# =============================================================================
# DNA alignment and VCF
# =============================================================================
rule dna_align:
    """Align fastq files with index by chosen aligner in config.yaml"""
    input: get_dna_align

rule dna_vcf:
    """Run vcf call, merge samples, create consensus, build snpeff db, annotate."""
    input: get_dna_vcf

rule dna_vcf_all:
    """A shortcut to run a full course with qc, aligner and vcf."""
    input:  
        get_qc,
        get_dna_align,
        get_dna_vcf

# =============================================================================
# DNA Ridigity Scoring
# =============================================================================
rule dna_rigid: 
    """Run dna rigidity score on fasta."""
    input: get_dna_rigid

# =============================================================================
# RNA Alignment and Expression Analysis
# =============================================================================
rule rna_align:
    """Align RNAseq reads using spliced aligner/ pseudo aligner and generate visualization tracks."""
    input:
        alignments = get_rna_align,
        bigwigs    = get_rna_bigwig,
        counts     = get_rna_counts
        
rule rna_exp:
    """Perform expression analysis using DESeq2 or edgeR."""
    input:
        get_rna_exp_analyser_output

rule exp_tools_compare:
    """Compare statistics between DESeq2 and edgeR outputs."""
    input:
        get_rna_tools_compare

rule rna_report:
    """
    Executes biological threshold filtering,model diagnostics, and global PCA variance plotting.
    """
    input:
        get_rna_report_outputs


rule rna_enrich:
    """
    Generate Heatmap and perform functional enrichment study.
    """
    input:
        get_rna_enrich_outputs

rule rna_all:
    """A shortcut to run a full course of RNAseq with qc, aligner, exp, report and enrich."""
    input:  
        get_qc,
        get_rna_align,
        get_rna_bigwig,
        get_rna_counts,
        get_rna_exp_analyser_output,
        get_rna_report_outputs,
        get_rna_enrich_outputs


# =============================================================================
# Chip-Seq Alignment and Peak Analysis
# =============================================================================

rule chip_align:
    """Align fastq files with index by chosen aligner in config.yaml"""
    input: get_chip_align