# ~~~~~ VCF Template~~~~~


# =============================================================================
# General Variables
# =============================================================================

#PRJN number (only used in getdata_sra)
PRJNUMBER: "PRJNA257197"

# Project name 
PRJNAME: "dna_ebola_2014"


# =============================================================================
# Ref variables 
# =============================================================================

REF: 
  SOURCE: "ncbi"
  SPECIES: "zaire_ebolavirus"
  ASSEMBLY: "GCF_000848505.1" # e.g. ncbi: GRCh38, ensembl: R64-2-1
  RELEASE: "2" # ncbi: p14 (patch #), ensemble: 83
  ACC: "GCF_000848505.1" # leave empty for ensembl